name: Compilador InfinityCalendar

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Esto te permite darle al botón de "Compilar" manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar codigo
      uses: actions/checkout@v4

    - name: Configurar Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Compilar con Maven
      run: mvn -B package --file pom.xml

    - name: Guardar el archivo .jar terminado
      uses: actions/upload-artifact@v4
      with:
        name: InfinityCalendar-JAR
        path: target/InfinityCalendar.jar
